# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
