# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_auto_20170607_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
