# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0010_auto_20170607_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
